import "../assets/sass/global.scss";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { fraunces } from "../ultils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fraunces.className} container`}>
        <Nav />
        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
